### ISSUE TITLE
Improve search algorithm

### ISSUE THREAD

**Issue by slrslr** [v4ww/Horizon#9]
Hello,

when i use Horizon site to search (it appears to have like 300MB database when i check site's (0) menu) for the phrase: blurhy
then it takes 50.169 seconds (old Pentium 1,6Ghz single thread CPU, 5400RPM HDD) to return the results. Can this be significantly reduced by using different method to store the data or different way to get the data from the db during search?

I have seen full CPU load during the search, then the CPU load dropped to like 30-60% (true that i have old CPU and its utilization is high even without search).

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 16.04 32bit
 - Browser Firefox 62.0
 - Zeronet Revision 3597

---

- [x] Add indexes
- [x] Make all queries using sql

**Comment by blurHY** [comment]
Currently it uses database,using javascript to filter data is also not possible.
Sometimes Horizon takes 1.5s to search.If zeronet client is busy,it will takes a few minutes.
The reason is that zeronet is single processing,so you can't open ZeroHello during querying.
I hope that will be implemented. https://github.com/HelloZeroNet/ZeroNet/issues/1620
If zeronet moves to python3, multi-processing will be possible, and full text search is also supported.
These two features are the solution.

But i can still improve a bit.

**Comment by blurHY** [comment]
@krixano 
I will imporve this by making all queries done with sql. Just use `group_concat()` then use js to cut string
